public enum Utility: String {
    // MARK: - A
    case accordion
    case accordionButton = "accordion-button"
    case accordionBody = "accordion-body"
    case accordionCollapse = "accordion-collapse"
    case accordionFlush = "accordion-flush"
    case accordionHeader = "accordion-header"
    case accordionItem = "accordion-item"
    
    case active = "active"
    
    case alert
    case alertDanger = "alert-danger"
    case alertDark = "alert-dark"
    case alertHeading = "alert-heading"
    case alertInfo = "alert-info"
    case alertLight = "alert-light"
    case alertLink = "alert-link"
    case alertPrimary = "alert-primary"
    case alertSecondary = "alert-secondary"
    case alertSuccess = "alert-success"
    case alertWarning = "alert-warning"
    
    case alignBaseline = "align-baseline"
    case alignTop = "align-top"
    case alignMiddle = "align-middle"
    case alignBottom = "align-bottom"
    case alignTextTop = "align-text-top"
    case alignTextBottom = "align-text-bottom"
    
    case alignContentStart = "align-content-start"
    case alignContentEnd = "align-content-end"
    case alignContentCenter = "align-content-center"
    case alignContentAround = "align-content-around"
    case alignContentStretch = "align-content-stretch"
    case alignContentSmStart = "align-content-sm-start"
    case alignContentSmEnd = "align-content-sm-end"
    case alignContentSmCenter = "align-content-sm-center"
    case alignContentSmAround = "align-content-sm-around"
    case alignContentSmStretch = "align-content-sm-stretch"
    case alignContentMdStart = "align-content-md-start"
    case alignContentMdEnd = "align-content-md-end"
    case alignContentMdCenter = "align-content-md-center"
    case alignContentMdAround = "align-content-md-around"
    case alignContentMdStretch = "align-content-md-stretch"
    case alignContentLgStart = "align-content-lg-start"
    case alignContentLgEnd = "align-content-lg-end"
    case alignContentLgCenter = "align-content-lg-center"
    case alignContentLgAround = "align-content-lg-around"
    case alignContentLgStretch = "align-content-lg-stretch"
    case alignContentXlStart = "align-content-xl-start"
    case alignContentXlEnd = "align-content-xl-end"
    case alignContentXlCenter = "align-content-xl-center"
    case alignContentXlAround = "align-content-xl-around"
    case alignContentXlStretch = "align-content-xl-stretch"
    case alignContentXxlStart = "align-content-xxl-start"
    case alignContentXxlEnd = "align-content-xxl-end"
    case alignContentXxlCenter = "align-content-xxl-center"
    case alignContentXxlAround = "align-content-xxl-around"
    case alignContentXxlStretch = "align-content-xxl-stretch"
    
    case alignItemsCenter = "align-items-center"
    case alignItemsEnd = "align-items-end"
    case alignItemsStart = "align-items-start"
    case alignItemsBaseline = "align-items-baseline"
    case alignItemsStretch = "align-items-stretch"
    case alignItemsSmStart = "align-items-sm-start"
    case alignItemsSmEnd = "align-items-sm-end"
    case alignItemsSmCenter = "align-items-sm-center"
    case alignItemsSmBaseline = "align-items-sm-baseline"
    case alignItemsSmStretch = "align-items-sm-stretch"
    case alignItemsMdStart = "align-items-md-start"
    case alignItemsMdEnd = "align-items-md-end"
    case alignItemsMdCenter = "align-items-md-center"
    case alignItemsMdBaseline = "align-items-md-baseline"
    case alignItemsMdStretch = "align-items-md-stretch"
    case alignItemsLgStart = "align-items-lg-start"
    case alignItemsLgEnd = "align-items-lg-end"
    case alignItemsLgCenter = "align-items-lg-center"
    case alignItemsLgBaseline = "align-items-lg-baseline"
    case alignItemsLgStretch = "align-items-lg-stretch"
    case alignItemsXlStart = "align-items-xl-start"
    case alignItemsXlEnd = "align-items-xl-end"
    case alignItemsXlCenter = "align-items-xl-center"
    case alignItemsXlBaseline = "align-items-xl-baseline"
    case alignItemsXlStretch = "align-items-xl-stretch"
    case alignItemsXxlStart = "align-items-xxl-start"
    case alignItemsXxlEnd = "align-items-xxl-end"
    case alignItemsXxlCenter = "align-items-xxl-center"
    case alignItemsXxlBaseline = "align-items-xxl-baseline"
    case alignItemsXxlStretch = "align-items-xxl-stretch"
    
    case alignSelfStart = "align-self-start"
    case alignSelfEnd = "align-self-end"
    case alignSelfCenter = "align-self-center"
    case alignSelfBaseline = "align-self-baseline"
    case alignSelfStretch = "align-self-stretch"
    case alignSelfSmStart = "align-self-sm-start"
    case alignSelfSmEnd = "align-self-sm-end"
    case alignSelfSmCenter = "align-self-sm-center"
    case alignSelfSmBaseline = "align-self-sm-baseline"
    case alignSelfSmStretch = "align-self-sm-stretch"
    case alignSelfMdStart = "align-self-md-start"
    case alignSelfMdEnd = "align-self-md-end"
    case alignSelfMdCenter = "align-self-md-center"
    case alignSelfMdBaseline = "align-self-md-baseline"
    case alignSelfMdStretch = "align-self-md-stretch"
    case alignSelfLgStart = "align-self-lg-start"
    case alignSelfLgEnd = "align-self-lg-end"
    case alignSelfLgCenter = "align-self-lg-center"
    case alignSelfLgBaseline = "align-self-lg-baseline"
    case alignSelfLgStretch = "align-self-lg-stretch"
    case alignSelfXlStart = "align-self-xl-start"
    case alignSelfXlEnd = "align-self-xl-end"
    case alignSelfXlCenter = "align-self-xl-center"
    case alignSelfXlBaseline = "align-self-xl-baseline"
    case alignSelfXlStretch = "align-self-xl-stretch"
    case alignSelfXxlStart = "align-self-xxl-start"
    case alignSelfXxlEnd = "align-self-xxl-end"
    case alignSelfXxlCenter = "align-self-xxl-center"
    case alignSelfXxlBaseline = "align-self-xxl-baseline"
    case alignSelfXxlStretch = "align-self-xxl-stretch"
    
    // MARK: - B
    case badge
    
    case bgDanger = "bg-danger"
    case bgDark = "bg-dark"
    case bgBody = "bg-body"
    case bgInfo = "bg-info"
    case bgLight = "bg-light"
    case bgPrimary = "bg-primary"
    case bgSecondary = "bg-secondary"
    case bgSuccess = "bg-success"
    case bgTransparent = "bg-transparent"
    case bgWarning = "bg-warning"
    case bgWhite = "bg-white"
    case bgGradient = "bg-gradient"
    
    case bgOpacity10 = "bg-opacity-10"
    case bgOpacity25 = "bg-opacity-25"
    case bgOpacity50 = "bg-opacity-50"
    case bgOpacity75 = "bg-opacity-75"
    
    case bgBlue = "bg-blue"
    case bgIndigo = "bg-indigo"
    case bgNavy = "bg-navy"
    case bgMaroon = "bg-maroon"
    case bgBrown = "bg-brown"
    case bgPurple = "bg-purple"
    case bgPink = "bg-pink"
    case bgMagenta = "bg-magenta"
    case bgRed = "bg-red"
    case bgOrange = "bg-orange"
    case bgYellow = "bg-yellow"
    case bgLime = "bg-lime"
    case bgGreen = "bg-green"
    case bgTeal = "bg-teal"
    case bgCyan = "bg-cyan"
    case bgBlack = "bg-black"
    case bgGray = "bg-gray"
    
    case blockquote
    case blockquoteFooter = "blockquote-footer"
    
    case body
    
    case borderPrimary = "border-primary"
    case borderSecondary = "border-secondary"
    case borderSuccess = "border-success"
    case borderDanger = "border-danger"
    case borderWarning = "border-warning"
    case borderInfo = "border-info"
    case borderLight = "border-light"
    case borderDark = "border-dark"
    case borderWhite = "border-white"
    
    case border
    case borderTop = "border-top"
    case borderEnd = "border-end"
    case borderBottom = "border-bottom"
    case borderStart = "border-start"
    
    case border1 = "border-1"
    case border2 = "border-2"
    case border3 = "border-3"
    case border4 = "border-4"
    case border5 = "border-5"
    
    case border0 = "border-0"
    case borderTop0 = "border-top-0"
    case borderEnd0 = "border-end-0"
    case borderBottom0 = "border-bottom-0"
    case borderStart0 = "border-start-0"
    
    case bottom0 = "bottom-0"
    case bottom50 = "bottom-50"
    case bottom100 = "bottom-100"
    
    case breadcrumb
    case breadcrumbItem = "breadcrumb-item"
    
    case btn
    case btnBlock = "btn-block"
    case btnCheck = "btn-check"
    case btnClose = "btn-close"
    case btnCloseWhite = "btn-close-white"
    case btnGroup = "btn-group"
    case btnGroupSm = "btn-group-sm"
    case btnGroupLg = "btn-group-lg"
    case btnGroupXl = "btn-group-xl"
    case btnGroupXxl = "btn-group-xxl"
    case btnGroupVertical = "btn-group-vertical"
    case btnLg = "btn-lg"
    case btnSm = "btn-sm"
    
    case btnDanger = "btn-danger"
    case btnDark = "btn-dark"
    case btnInfo = "btn-info"
    case btnLight = "btn-light"
    case btnLink = "btn-link"
    case btnPrimary = "btn-primary"
    case btnSecondary = "btn-secondary"
    case btnToolbar = "btn-toolbar"
    case btnSuccess = "btn-success"
    case btnWarning = "btn-warning"
    
    case btnOutlineDanger = "btn-outline-danger"
    case btnOutlineDark = "btn-outline-dark"
    case btnOutlineInfo = "btn-outline-info"
    case btnOutlineLight = "btn-outline-light"
    case btnOutlinePrimary = "btn-outline-primary"
    case btnOutlineSecondary = "btn-outline-secondary"
    case btnOutlineSuccess = "btn-outline-success"
    case btnOutlineWarning = "btn-outline-warning"
    
    case button
    
    // MARK: - C
    case captionTop = "caption-top"
    case card
    case cardBody = "card-body"
    case cardFooter = "card-footer"
    case cardHeader = "card-header"
    case cardHeaderTabs = "card-header-tabs"
    case cardHeaderPills = "card-header-pills"
    case cardImg = "card-img"
    case cardImgOverlay = "card-img-overlay"
    case cardImgTop = "card-img-top"
    case cardImgBottom = "card-img-bottom"
    case cardLink = "card-link"
    case cardSubtitle = "card-subtitle"
    case cardText = "card-text"
    case cardTitle = "card-title"
    
    case carousel
    case carouselCaption = "carousel-caption"
    case carouselControlPrev = "carousel-control-prev"
    case carouselControlNext = "carousel-control-next"
    case carouselDark = "carousel-dark"
    case carouselFade = "carousel-fade"
    case carouselIndicators = "carousel-indicators"
    case carouselInner = "carousel-inner"
    case carouselItem = "carousel-item"
    case carouselControlPrevIcon = "carousel-control-prev-icon"
    case carouselControlNextIcon = "carousel-control-next-icon"
    
    case clearfix
    
    case collapse
    case collapseHorizontal = "collapse-horizontal"
    case collapsed
    
    case col
    case colAuto = "col-auto"
    
    case col2 = "col-2"
    case col3 = "col-3"
    case col4 = "col-4"
    case col5 = "col-5"
    case col6 = "col-6"
    case col7 = "col-7"
    case col8 = "col-8"
    case col9 = "col-9"
    case col10 = "col-10"
    case col11 = "col-11"
    case col12 = "col-12"
    
    case colSm = "col-sm"
    case colSm2 = "col-sm-2"
    case colSm3 = "col-sm-3"
    case colSm4 = "col-sm-4"
    case colSm5 = "col-sm-5"
    case colSm6 = "col-sm-6"
    case colSm7 = "col-sm-7"
    case colSm8 = "col-sm-8"
    case colSm9 = "col-sm-9"
    case colSm10 = "col-sm-10"
    case colSm11 = "col-sm-11"
    case colSm12 = "col-sm-12"
    
    case colMd = "col-md"
    case colMd2 = "col-md-2"
    case colMd3 = "col-md-3"
    case colMd4 = "col-md-4"
    case colMd5 = "col-md-5"
    case colMd6 = "col-md-6"
    case colMd7 = "col-md-7"
    case colMd8 = "col-md-8"
    case colMd9 = "col-md-9"
    case colMd10 = "col-md-10"
    case colMd11 = "col-md-11"
    case colMd12 = "col-md-12"
    
    case colLg = "col-lg"
    case colLg2 = "col-lg-2"
    case colLg3 = "col-lg-3"
    case colLg4 = "col-lg-4"
    case colLg5 = "col-lg-5"
    case colLg6 = "col-lg-6"
    case colLg7 = "col-lg-7"
    case colLg8 = "col-lg-8"
    case colLg9 = "col-lg-9"
    case colLg10 = "col-lg-10"
    case colLg11 = "col-lg-11"
    case colLg12 = "col-lg-12"
    
    case colXl = "col-xl"
    case colXl2 = "col-xl-2"
    case colXl3 = "col-xl-3"
    case colXl4 = "col-xl-4"
    case colXl5 = "col-xl-5"
    case colXl6 = "col-xl-6"
    case colXl7 = "col-xl-7"
    case colXl8 = "col-xl-8"
    case colXl9 = "col-xl-9"
    case colXl10 = "col-xl-10"
    case colXl11 = "col-xl-11"
    case colXl12 = "col-xl-12"
    
    case colXxl = "col-xxl"
    case colXxl2 = "col-xxl-2"
    case colXxl3 = "col-xxl-3"
    case colXxl4 = "col-xxl-4"
    case colXxl5 = "col-xxl-5"
    case colXxl6 = "col-xxl-6"
    case colXxl7 = "col-xxl-7"
    case colXxl8 = "col-xxl-8"
    case colXxl9 = "col-xxl-9"
    case colXxl10 = "col-xxl-10"
    case colXxl11 = "col-xxl-11"
    case colXxl12 = "col-xxl-12"
    
    case colFormLabel = "col-form-label"
    case colFormLabelSm = "col-form-label-sm"
    case colFormLabelLg = "col-form-label-lg"
    
    case container
    case containerSm = "container-sm"
    case containerMd = "container-md"
    case containerLg = "container-lg"
    case containerXl = "container-xl"
    case containerXxl = "container-xxl"
    case containerFluid = "container-fluid"
    
    // MARK: - D
    case dNone = "d-none"
    case dInline = "d-inline"
    case dInlineBlock = "d-inline-block"
    case dBlock = "d-block"
    case dGrid = "d-grid"
    case dTable = "d-table"
    case dTableCell = "d-table-cell"
    case dTableRow = "d-table-row"
    case dFlex = "d-flex"
    case dInlineFlex = "d-inline-flex"
    case dSmNone = "d-sm-none"
    case dSmInline = "d-sm-inline"
    case dSmInlineBlock = "d-sm-inline-block"
    case dSmBlock = "d-sm-block"
    case dSmGrid = "d-sm-grid"
    case dSmTable = "d-sm-table"
    case dSmTableCell = "d-sm-table-cell"
    case dSmTableRow = "d-sm-table-row"
    case dSmFlex = "d-sm-flex"
    case dSmInlineFlex = "d-sm-inline-flex"
    case dMdNone = "d-md-none"
    case dMdInline = "d-md-inline"
    case dMdInlineBlock = "d-md-inline-block"
    case dMdBlock = "d-md-block"
    case dMdGrid = "d-md-grid"
    case dMdTable = "d-md-table"
    case dMdTableCell = "d-md-table-cell"
    case dMdTableRow = "d-md-table-row"
    case dMdFlex = "d-md-flex"
    case dMdInlineFlex = "d-md-inline-flex"
    case dLgNone = "d-lg-none"
    case dLgInline = "d-lg-inline"
    case dLgInlineBlock = "d-lg-inline-block"
    case dLgBlock = "d-lg-block"
    case dLgGrid = "d-lg-grid"
    case dLgTable = "d-lg-table"
    case dLgTableCell = "d-lg-table-cell"
    case dLgTableRow = "d-lg-table-row"
    case dLgFlex = "d-lg-flex"
    case dLgInlineFlex = "d-lg-inline-flex"
    case dXlNone = "d-xl-none"
    case dXlInline = "d-xl-inline"
    case dXlInlineBlock = "d-xl-inline-block"
    case dXlBlock = "d-xl-block"
    case dXlGrid = "d-xl-grid"
    case dXlTable = "d-xl-table"
    case dXlTableCell = "d-xl-table-cell"
    case dXlTableRow = "d-xl-table-row"
    case dXlFlex = "d-xl-flex"
    case dXlInlineFlex = "d-xl-inline-flex"
    case dXxlNone = "d-xxl-none"
    case dXxlInline = "d-xxl-inline"
    case dXxlInlineBlock = "d-xxl-inline-block"
    case dXxlBlock = "d-xxl-block"
    case dXxlGrid = "d-xxl-grid"
    case dXxlTable = "d-xxl-table"
    case dXxlTableCell = "d-xxl-table-cell"
    case dXxlTableRow = "d-xxl-table-row"
    case dXxlFlex = "d-xxl-flex"
    case dXxlInlineFlex = "d-xxl-inline-flex"
    
    case dPrintNone = "d-print-none"
    case dPrintInline = "d-print-inline"
    case dPrintInlineBlock = "d-print-inline-block"
    case dPrintBlock = "d-print-block"
    case dPrintGrid = "d-print-grid"
    case dPrintTable = "d-print-table"
    case dPrintTableRow = "d-print-table-row"
    case dPrintTableCell = "d-print-table-cell"
    case dPrintFlex = "d-print-flex"
    case dPrintInlineFlex = "d-print-inline-flex"
    
    case disabled = "disabled"
    
    case display1 = "display-1"
    case display2 = "display-2"
    case display3 = "display-3"
    case display4 = "display-4"
    case display5 = "display-5"
    case display6 = "display-6"
    
    case dropdown
    case dropdownDivider = "dropdown-divider"
    case dropdownHeader = "dropdown-header"
    case dropdownItem = "dropdown-item"
    case dropdownItemText = "dropdown-item-text"
    case dropdownMenu = "dropdown-menu"
    case dropdownMenuDark = "dropdown-menu-dark"
    
    case dropdownMenuEnd = "dropdown-menu-end"
    case dropdownMenuSmEnd = "dropdown-menu-sm-end"
    case dropdownMenuMdEnd = "dropdown-menu-md-end"
    case dropdownMenuLgEnd = "dropdown-menu-lg-end"
    case dropdownMenuXlEnd = "dropdown-menu-xl-end"
    case dropdownMenuXxlEnd = "dropdown-menu-xxl-end"
    case dropdownMenuSmStart = "dropdown-menu-sm-start"
    case dropdownMenuMdStart = "dropdown-menu-md-start"
    case dropdownMenuLgStart = "dropdown-menu-lg-start"
    case dropdownMenuXlStart = "dropdown-menu-xl-start"
    case dropdownMenuXxlStart = "dropdown-menu-xxl-start"
    
    case dropdownToggle = "dropdown-toggle"
    case dropdownToggleSplit = "dropdown-toggle-split"
    
    case dropend
    case dropup
    case dropstart
    
    // MARK: - E
    case end0 = "end-0"
    case end50 = "end-50"
    case end100 = "end-100"
    
    // MARK: - F
    case fade
    case figure
    case figureCaption = "figure-caption"
    case figureImg = "figure-img"
    
    case fixedTop = "fixed-top"
    case fixedBottom = "fixed-bottom"
    
    case flexRow = "flex-row"
    case flexRowReverse = "flex-row-reverse"
    case flexColumn = "flex-column"
    case flexColumnReverse = "flex-column-reverse"
    case flexSmRow = "flex-sm-row"
    case flexSmRowReverse = "flex-sm-row-reverse"
    case flexSmColumn = "flex-sm-column"
    case flexSmColumnReverse = "flex-sm-column-reverse"
    case flexMdRow = "flex-md-row"
    case flexMdRowReverse = "flex-md-row-reverse"
    case flexMdColumn = "flex-md-column"
    case flexMdColumnReverse = "flex-md-column-reverse"
    case flexLgRow = "flex-lg-row"
    case flexLgRowReverse = "flex-lg-row-reverse"
    case flexLgColumn = "flex-lg-column"
    case flexLgColumnReverse = "flex-lg-column-reverse"
    case flexXlRow = "flex-xl-row"
    case flexXlRowReverse = "flex-xl-row-reverse"
    case flexXlColumn = "flex-xl-column"
    case flexXlColumnReverse = "flex-xl-column-reverse"
    case flexXxlRow = "flex-xxl-row"
    case flexXxlRowReverse = "flex-xxl-row-reverse"
    case flexXxlColumn = "flex-xxl-column"
    case flexXxlColumnReverse = "flex-xxl-column-reverse"
    
    case flexFill = "flex-fill"
    case flexSmFill = "flex-sm-fill"
    case flexMdFill = "flex-md-fill"
    case flexLgFill = "flex-lg-fill"
    case flexXlFill = "flex-xl-fill"
    case flexXxlFill = "flex-xxl-fill"
    
    case flexGrow0 = "flex-grow-0"
    case flexGrow1 = "flex-grow-1"
    case flexSmGrow0 = "flex-sm-grow-0"
    case flexSmGrow1 = "flex-sm-grow-1"
    case flexMdGrow0 = "flex-md-grow-0"
    case flexMdGrow1 = "flex-md-grow-1"
    case flexLgGrow0 = "flex-lg-grow-0"
    case flexLgGrow1 = "flex-lg-grow-1"
    case flexXlGrow0 = "flex-xl-grow-0"
    case flexXlGrow1 = "flex-xl-grow-1"
    case flexXxlGrow0 = "flex-xxl-grow-0"
    case flexXxlGrow1 = "flex-xxl-grow-1"
    case flexShrink0 = "flex-shrink-0"
    case flexShrink1 = "flex-shrink-1"
    case flexSmShrink0 = "flex-sm-shrink-0"
    case flexSmShrink1 = "flex-sm-shrink-1"
    case flexMdShrink0 = "flex-md-shrink-0"
    case flexMdShrink1 = "flex-md-shrink-1"
    case flexLgShrink0 = "flex-lg-shrink-0"
    case flexLgShrink1 = "flex-lg-shrink-1"
    case flexXlShrink0 = "flex-xl-shrink-0"
    case flexXlShrink1 = "flex-xl-shrink-1"
    case flexXxlShrink0 = "flex-xxl-shrink-0"
    case flexXxlShrink1 = "flex-xxl-shrink-1"
    
    case flexNowrap = "flex-nowrap"
    case flexWrap = "flex-wrap"
    case flexWrapReverse = "flex-wrap-reverse"
    case flexSmNowrap = "flex-sm-nowrap"
    case flexSmWrap = "flex-sm-wrap"
    case flexSmWrapReverse = "flex-sm-wrap-reverse"
    case flexMdNowrap = "flex-md-nowrap"
    case flexMdWrap = "flex-md-wrap"
    case flexMdWrapReverse = "flex-md-wrap-reverse"
    case flexLgNowrap = "flex-lg-nowrap"
    case flexLgWrap = "flex-lg-wrap"
    case flexLgWrapReverse = "flex-lg-wrap-reverse"
    case flexXlNowrap = "flex-xl-nowrap"
    case flexXlWrap = "flex-xl-wrap"
    case flexXlWrapReverse = "flex-xl-wrap-reverse"
    case flexXxlNowrap = "flex-xxl-nowrap"
    case flexXxlWrap = "flex-xxl-wrap"
    case flexXxlWrapReverse = "flex-xxl-wrap-reverse"
    
    case floatStart = "float-start"
    case floatEnd = "float-end"
    case floatNone = "float-none"
    case floatSmStart = "float-sm-start"
    case floatSmEnd = "float-sm-end"
    case floatSmNone = "float-sm-none"
    case floatMdStart = "float-md-start"
    case floatMdEnd = "float-md-end"
    case floatMdNone = "float-md-none"
    case floatLgStart = "float-lg-start"
    case floatLgEnd = "float-lg-end"
    case floatLgNone = "float-lg-none"
    case floatXlStart = "float-xl-start"
    case floatXlEnd = "float-xl-end"
    case floatXlNone = "float-xl-none"
    case floatXxlStart = "float-xxl-start"
    case floatXxlEnd = "float-xxl-end"
    case floatXxlNone = "float-xxl-none"
    
    case focus
    
    case fontMonospace = "font-monospace"
    
    case formCheck = "form-check"
    case formCheckInline = "form-check-inline"
    case formCheckInput = "form-check-input"
    case formCheckLabel = "form-check-label"
    case formControl = "form-control"
    case formControlLg = "form-control-lg"
    case formControlSm = "form-control-sm"
    case formControlPlaintext = "form-control-plaintext"
    case formControlColor = "form-control-color"
    case formFloating = "form-floating"
    case formLabel = "form-label"
    case formRange = "form-range"
    case formSelect = "form-select"
    case formSelectLg = "form-select-lg"
    case formSelectSm = "form-select-sm"
    case formSwitch = "form-switch"
    case formText = "form-text"
    
    case fs1 = "fs-1"
    case fs2 = "fs-2"
    case fs3 = "fs-3"
    case fs4 = "fs-4"
    case fs5 = "fs-5"
    case fs6 = "fs-6"

    case fstItalic = "fst-italic"
    case fstNormal = "fst-normal"

    case fwBold = "fw-bold"
    case fwBolder = "fw-bolder"
    case fwSemibold = "fw-semibold"
    case fwNormal = "fw-normal"
    case fwLight = "fw-light"
    case fwLighter = "fw-lighter"
    
    // MARK: - G
    case gap0 = "gap-0"
    case gap1 = "gap-1"
    case gap2 = "gap-2"
    case gap3 = "gap-3"
    case gap4 = "gap-4"
    case gap5 = "gap-5"
    
    case gapXs0 = "gap-xs-0"
    case gapSm0 = "gap-sm-0"
    case gapMd0 = "gap-md-0"
    case gapLg0 = "gap-lg-0"
    case gapXl0 = "gap-xl-0"
    case gapXxl0 = "gap-xxl-0"

    case gapXs1 = "gap-xs-1"
    case gapSm1 = "gap-sm-1"
    case gapMd1 = "gap-md-1"
    case gapLg1 = "gap-lg-1"
    case gapXl1 = "gap-xl-1"
    case gapXxl1 = "gap-xxl-1"

    case gapXs2 = "gap-xs-2"
    case gapSm2 = "gap-sm-2"
    case gapMd2 = "gap-md-2"
    case gapLg2 = "gap-lg-2"
    case gapXl2 = "gap-xl-2"
    case gapXxl2 = "gap-xxl-2"

    case gapXs3 = "gap-xs-3"
    case gapSm3 = "gap-sm-3"
    case gapMd3 = "gap-md-3"
    case gapLg3 = "gap-lg-3"
    case gapXl3 = "gap-xl-3"
    case gapXxl3 = "gap-xxl-3"

    case gapXs4 = "gap-xs-4"
    case gapSm4 = "gap-sm-4"
    case gapMd4 = "gap-md-4"
    case gapLg4 = "gap-lg-4"
    case gapXl4 = "gap-xl-4"
    case gapXxl4 = "gap-xxl-4"

    case gapXs5 = "gap-xs-5"
    case gapSm5 = "gap-sm-5"
    case gapMd5 = "gap-md-5"
    case gapLg5 = "gap-lg-5"
    case gapXl5 = "gap-xl-5"
    case gapXxl5 = "gap-xxl-5"
    
    case grid
    case gCol2 = "g-col-2"
    case gColSm2 = "g-col-sm-2"
    case gColMd2 = "g-col-md-2"
    case gColLg2 = "g-col-lg-2"
    case gColXl2 = "g-col-xl-2"
    case gColXxl2 = "g-col-xxl-2"
    
    case gCol4 = "g-col-4"
    case gColSm4 = "g-col-sm-4"
    case gColMd4 = "g-col-md-4"
    case gColLg4 = "g-col-lg-4"
    case gColXl4 = "g-col-xl-4"
    case gColXxl4 = "g-col-xxl-4"
    
    case gCol6 = "g-col-6"
    case gColSm6 = "g-col-sm-6"
    case gColMd6 = "g-col-md-6"
    case gColLg6 = "g-col-lg-6"
    case gColXl6 = "g-col-xl-6"
    case gColXxl6 = "g-col-xxl-6"
    
    case gStart1 = "g-start-1"
    case gStart2 = "g-start-2"
    case gStart3 = "g-start-3"
    case gStart4 = "g-start-4"
    case gStart5 = "g-start-5"
    case gStart6 = "g-start-6"
    
    case gEnd1 = "g-end-1"
    case gEnd2 = "g-end-2"
    case gEnd3 = "g-end-3"
    case gEnd4 = "g-end-4"
    case gEnd5 = "g-end-5"
    case gEnd6 = "g-end-6"
    
    case g0 = "g-0"
    
    case g1 = "g-1"
    case gSm1 = "g-sm-1"
    case gMd1 = "g-md-1"
    case gLg1 = "g-lg-1"
    case gXl1 = "g-xl-1"
    case gXxl1 = "g-xxl-1"
    
    case g2 = "g-2"
    case gSm2 = "g-sm-2"
    case gMd2 = "g-md-2"
    case gLg2 = "g-lg-2"
    case gXl2 = "g-xl-2"
    case gXxl2 = "g-xxl-2"
    
    case g3 = "g-3"
    case gSm3 = "g-sm-3"
    case gMd3 = "g-md-3"
    case gLg3 = "g-lg-3"
    case gXl3 = "g-xl-3"
    case gXxl3 = "g-xxl-3"
    
    case g4 = "g-4"
    case gSm4 = "g-sm-4"
    case gMd4 = "g-md-4"
    case gLg4 = "g-lg-4"
    case gXl4 = "g-xl-4"
    case gXxl4 = "g-xxl-4"
    
    case g5 = "g-5"
    case gSm5 = "g-sm-5"
    case gMd5 = "g-md-5"
    case gLg5 = "g-lg-5"
    case gXl5 = "g-xl-5"
    case gXxl5 = "g-xxl-5"
    
    case gx1 = "gx-1"
    case gxSm1 = "gx-sm-1"
    case gxMd1 = "gx-md-1"
    case gxLg1 = "gx-lg-1"
    case gxXl1 = "gx-xl-1"
    case gxXxl1 = "gx-xxl-1"
    
    case gx2 = "gx-2"
    case gxSm2 = "gx-sm-2"
    case gxMd2 = "gx-md-2"
    case gxLg2 = "gx-lg-2"
    case gxXl2 = "gx-xl-2"
    case gxXxl2 = "gx-xxl-2"
    
    case gx3 = "gx-3"
    case gxSm3 = "gx-sm-3"
    case gxMd3 = "gx-md-3"
    case gxLg3 = "gx-lg-3"
    case gxXl3 = "gx-xl-3"
    case gxXxl3 = "gx-xxl-3"
    
    case gx4 = "gx-4"
    case gxSm4 = "gx-sm-4"
    case gxMd4 = "gx-md-4"
    case gxLg4 = "gx-lg-4"
    case gxXl4 = "gx-xl-4"
    case gxXxl4 = "gx-xxl-4"
    
    case gx5 = "gx-5"
    case gxSm5 = "gx-sm-5"
    case gxMd5 = "gx-md-5"
    case gxLg5 = "gx-lg-5"
    case gxXl5 = "gx-xl-5"
    case gxXxl5 = "gx-xxl-5"
    
    case gy1 = "gy-1"
    case gySm1 = "gy-sm-1"
    case gyMd1 = "gy-md-1"
    case gyLg1 = "gy-lg-1"
    case gyXl1 = "gy-xl-1"
    case gyXxl1 = "gy-xxl-1"
    
    case gy2 = "gy-2"
    case gySm2 = "gy-sm-2"
    case gyMd2 = "gy-md-2"
    case gyLg2 = "gy-lg-2"
    case gyXl2 = "gy-xl-2"
    case gyXxl2 = "gy-xxl-2"
    
    case gy3 = "gy-3"
    case gySm3 = "gy-sm-3"
    case gyMd3 = "gy-md-3"
    case gyLg3 = "gy-lg-3"
    case gyXl3 = "gy-xl-3"
    case gyXxl3 = "gy-xxl-#"
    
    case gy4 = "gy-4"
    case gySm4 = "gy-sm-4"
    case gyMd4 = "gy-md-4"
    case gyLg4 = "gy-lg-4"
    case gyXl4 = "gy-xl-4"
    case gyXxl4 = "gy-xxl-4"
    
    case gy5 = "gy-5"
    case gySm5 = "gy-sm-5"
    case gyMd5 = "gy-md-5"
    case gyLg5 = "gy-lg-5"
    case gyXl5 = "gy-xl-5"
    case gyXxl5 = "gy-xxl-5"
    
    // MARK: - H
    case h1
    case h2
    case h3
    case h4
    case h5
    case h6
    
    case h25 = "h-25"
    case h50 = "h-50"
    case h75 = "h-75"
    case h100 = "h-100"
    case hAuto = "h-auto"
    
    case hstack
    
    // MARK: - I
    case icon = "icon"
    case imgFluid = "img-fluid"
    case imgThumbnail = "img-thumbnail"
    
    case initialism
    
    case inputGroup = "input-group"
    case inputGroupSm = "input-group-sm"
    case inputGroupMd = "input-group-md"
    case inputGroupLg = "input-group-lg"
    case inputGroupXl = "input-group-xl"
    case inputGroupXxl = "input-group-xxl"
    case inputGroupText = "input-group-text"
    
    case invalidFeedback = "invalid-feedback"
    case isValid = "is-valid"
    case isInvalid = "is-invalid"
    case invisible
    
    // MARK: - J
    case justifyContentStart = "justify-content-start"
    case justifyContentEnd = "justify-content-end"
    case justifyContentCenter = "justify-content-center"
    case justifyContentBetween = "justify-content-between"
    case justifyContentAround = "justify-content-around"
    case justifyContentEvenly = "justify-content-evenly"
    case justifyContentSmStart = "justify-content-sm-start"
    case justifyContentSmEnd = "justify-content-sm-end"
    case justifyContentSmCenter = "justify-content-sm-center"
    case justifyContentSmBetween = "justify-content-sm-between"
    case justifyContentSmAround = "justify-content-sm-around"
    case justifyContentSmEvenly = "justify-content-sm-evenly"
    case justifyContentMdStart = "justify-content-md-start"
    case justifyContentMdEnd = "justify-content-md-end"
    case justifyContentMdCenter = "justify-content-md-center"
    case justifyContentMdBetween = "justify-content-md-between"
    case justifyContentMdAround = "justify-content-md-around"
    case justifyContentMdEvenly = "justify-content-md-evenly"
    case justifyContentLgStart = "justify-content-lg-start"
    case justifyContentLgEnd = "justify-content-lg-end"
    case justifyContentLgCenter = "justify-content-lg-center"
    case justifyContentLgBetween = "justify-content-lg-between"
    case justifyContentLgAround = "justify-content-lg-around"
    case justifyContentLgEvenly = "justify-content-lg-evenly"
    case justifyContentXlStart = "justify-content-xl-start"
    case justifyContentXlEnd = "justify-content-xl-end"
    case justifyContentXlCenter = "justify-content-xl-center"
    case justifyContentXlBetween = "justify-content-xl-between"
    case justifyContentXlAround = "justify-content-xl-around"
    case justifyContentXlEvenly = "justify-content-xl-evenly"
    case justifyContentXxlStart = "justify-content-xxl-start"
    case justifyContentXxlEnd = "justify-content-xxl-end"
    case justifyContentXxlCenter = "justify-content-xxl-center"
    case justifyContentXxlBetween = "justify-content-xxl-between"
    case justifyContentXxlAround = "justify-content-xxl-around"
    case justifyContentXxlEvenly = "justify-content-xxl-evenly"

    
    // MARK: - L
    case lead
    case left = "left"
    
    case linkPrimary = "link-primary"
    case linkSecondary = "link-secondary"
    case linkSuccess = "link-success"
    case linkDanger = "link-danger"
    case linkWarning = "link-warning"
    case linkInfo = "link-info"
    case linkLight = "link-light"
    case linkDark = "link-dark"
    
    case listGroup = "list-group"
    case listGroupFlush = "list-group-flush"
    case listGroupHorizontal = "list-group-horizontal"
    case listGroupNumbered = "list-group-numbered"
    case listGroupItem = "list-group-item"
    case listGroupItemPrimary = "list-group-item-primary"
    case listGroupItemSecondary = "list-group-item-secondary"
    case listGroupItemSuccess = "list-group-item-success"
    case listGroupItemDanger = "list-group-item-danger"
    case listGroupItemWarning = "list-group-item-warning"
    case listGroupItemInfo = "list-group-item-info"
    case listGroupItemLight = "list-group-item-light"
    case listGroupItemDark = "list-group-item-dark"
    case listGroupItemAction = "list-group-item-action"
    case listInline = "list-inline"
    case listInlineItem = "list-inline-item"
    case listUnstyled = "list-unstyled"
    
    case lh1 = "lh-1"
    case lhSm = "lh-sm"
    case lhBase = "lh-base"
    case lhLg = "lh-lg"
    
    // MARK: - M
    case multiCollapse = "multi-collapse"
    
    case modal
    case modalBody = "modal-body"
    case modalDialog = "modal-dialog"
    case modalDialogCentered = "modal-dialog-centered"
    case modalDialogScrollable = "modal-dialog-scrollable"
    case modalContent = "modal-content"
    case modalFooter = "modal-footer"
    case modalHeader = "modal-header"
    case modalTitle = "modal-title"
    
    case modalFullscreen = "modal-fullscreen"
    case modalFullscreenSmDown = "modal-fullscreen-sm-down"
    case modalFullscreenMdDown = "modal-fullscreen-md-down"
    case modalFullscreenLgDown = "modal-fullscreen-lg-down"
    case modalFullscreenXlDown = "modal-fullscreen-xl-down"
    case modalFullscreenXxlDown = "modal-fullscreen-xxl-down"
    
    case modalSm = "modal-sm"
    case modalLg = "modal-lg"
    case modalXl = "modal-xl"
    
    case mt0 = "mt-0"
    case mt1 = "mt-1"
    case mt2 = "mt-2"
    case mt3 = "mt-3"
    case mt4 = "mt-4"
    case mt5 = "mt-5"
    case mtAuto = "mt-auto"
    case mtSm0 = "mt-sm-0"
    case mtSm1 = "mt-sm-1"
    case mtSm2 = "mt-sm-2"
    case mtSm3 = "mt-sm-3"
    case mtSm4 = "mt-sm-4"
    case mtSm5 = "mt-sm-5"
    case mtSmAuto = "mt-sm-auto"
    case mtMd0 = "mt-md-0"
    case mtMd1 = "mt-md-1"
    case mtMd2 = "mt-md-2"
    case mtMd3 = "mt-md-3"
    case mtMd4 = "mt-md-4"
    case mtMd5 = "mt-md-5"
    case mtMdAuto = "mt-md-auto"
    case mtLg0 = "mt-lg-0"
    case mtLg1 = "mt-lg-1"
    case mtLg2 = "mt-lg-2"
    case mtLg3 = "mt-lg-3"
    case mtLg4 = "mt-lg-4"
    case mtLg5 = "mt-lg-5"
    case mtLgAuto = "mt-lg-auto"
    case mtXl0 = "mt-xl-0"
    case mtXl1 = "mt-xl-1"
    case mtXl2 = "mt-xl-2"
    case mtXl3 = "mt-xl-3"
    case mtXl4 = "mt-xl-4"
    case mtXl5 = "mt-xl-5"
    case mtXlAuto = "mt-xl-auto"
    case mtXxl0 = "mt-xxl-0"
    case mtXxl1 = "mt-xxl-1"
    case mtXxl2 = "mt-xxl-2"
    case mtXxl3 = "mt-xxl-3"
    case mtXxl4 = "mt-xxl-4"
    case mtXxl5 = "mt-xxl-5"
    case mtXxlAuto = "mt-xxl-auto"
    case mb0 = "mb-0"
    case mb1 = "mb-1"
    case mb2 = "mb-2"
    case mb3 = "mb-3"
    case mb4 = "mb-4"
    case mb5 = "mb-5"
    case mbAuto = "mb-auto"
    case mbSm0 = "mb-sm-0"
    case mbSm1 = "mb-sm-1"
    case mbSm2 = "mb-sm-2"
    case mbSm3 = "mb-sm-3"
    case mbSm4 = "mb-sm-4"
    case mbSm5 = "mb-sm-5"
    case mbSmAuto = "mb-sm-auto"
    case mbMd0 = "mb-md-0"
    case mbMd1 = "mb-md-1"
    case mbMd2 = "mb-md-2"
    case mbMd3 = "mb-md-3"
    case mbMd4 = "mb-md-4"
    case mbMd5 = "mb-md-5"
    case mbMdAuto = "mb-md-auto"
    case mbLg0 = "mb-lg-0"
    case mbLg1 = "mb-lg-1"
    case mbLg2 = "mb-lg-2"
    case mbLg3 = "mb-lg-3"
    case mbLg4 = "mb-lg-4"
    case mbLg5 = "mb-lg-5"
    case mbLgAuto = "mb-lg-auto"
    case mbXl0 = "mb-xl-0"
    case mbXl1 = "mb-xl-1"
    case mbXl2 = "mb-xl-2"
    case mbXl3 = "mb-xl-3"
    case mbXl4 = "mb-xl-4"
    case mbXl5 = "mb-xl-5"
    case mbXlAuto = "mb-xl-auto"
    case mbXxl0 = "mb-xxl-0"
    case mbXxl1 = "mb-xxl-1"
    case mbXxl2 = "mb-xxl-2"
    case mbXxl3 = "mb-xxl-3"
    case mbXxl4 = "mb-xxl-4"
    case mbXxl5 = "mb-xxl-5"
    case mbXxlAuto = "mb-xxl-auto"
    case ms0 = "ms-0"
    case ms1 = "ms-1"
    case ms2 = "ms-2"
    case ms3 = "ms-3"
    case ms4 = "ms-4"
    case ms5 = "ms-5"
    case msAuto = "ms-auto"
    case msSm0 = "ms-sm-0"
    case msSm1 = "ms-sm-1"
    case msSm2 = "ms-sm-2"
    case msSm3 = "ms-sm-3"
    case msSm4 = "ms-sm-4"
    case msSm5 = "ms-sm-5"
    case msSmAuto = "ms-sm-auto"
    case msMd0 = "ms-md-0"
    case msMd1 = "ms-md-1"
    case msMd2 = "ms-md-2"
    case msMd3 = "ms-md-3"
    case msMd4 = "ms-md-4"
    case msMd5 = "ms-md-5"
    case msMdAuto = "ms-md-auto"
    case msLg0 = "ms-lg-0"
    case msLg1 = "ms-lg-1"
    case msLg2 = "ms-lg-2"
    case msLg3 = "ms-lg-3"
    case msLg4 = "ms-lg-4"
    case msLg5 = "ms-lg-5"
    case msLgAuto = "ms-lg-auto"
    case msXl0 = "ms-xl-0"
    case msXl1 = "ms-xl-1"
    case msXl2 = "ms-xl-2"
    case msXl3 = "ms-xl-3"
    case msXl4 = "ms-xl-4"
    case msXl5 = "ms-xl-5"
    case msXlAuto = "ms-xl-auto"
    case msXxl0 = "ms-xxl-0"
    case msXxl1 = "ms-xxl-1"
    case msXxl2 = "ms-xxl-2"
    case msXxl3 = "ms-xxl-3"
    case msXxl4 = "ms-xxl-4"
    case msXxl5 = "ms-xxl-5"
    case msXxlAuto = "ms-xxl-auto"
    case me0 = "me-0"
    case me1 = "me-1"
    case me2 = "me-2"
    case me3 = "me-3"
    case me4 = "me-4"
    case me5 = "me-5"
    case meAuto = "me-auto"
    case meSm0 = "me-sm-0"
    case meSm1 = "me-sm-1"
    case meSm2 = "me-sm-2"
    case meSm3 = "me-sm-3"
    case meSm4 = "me-sm-4"
    case meSm5 = "me-sm-5"
    case meSmAuto = "me-sm-auto"
    case meMd0 = "me-md-0"
    case meMd1 = "me-md-1"
    case meMd2 = "me-md-2"
    case meMd3 = "me-md-3"
    case meMd4 = "me-md-4"
    case meMd5 = "me-md-5"
    case meMdAuto = "me-md-auto"
    case meLg0 = "me-lg-0"
    case meLg1 = "me-lg-1"
    case meLg2 = "me-lg-2"
    case meLg3 = "me-lg-3"
    case meLg4 = "me-lg-4"
    case meLg5 = "me-lg-5"
    case meLgAuto = "me-lg-auto"
    case meXl0 = "me-xl-0"
    case meXl1 = "me-xl-1"
    case meXl2 = "me-xl-2"
    case meXl3 = "me-xl-3"
    case meXl4 = "me-xl-4"
    case meXl5 = "me-xl-5"
    case meXlAuto = "me-xl-auto"
    case meXxl0 = "me-xxl-0"
    case meXxl1 = "me-xxl-1"
    case meXxl2 = "me-xxl-2"
    case meXxl3 = "me-xxl-3"
    case meXxl4 = "me-xxl-4"
    case meXxl5 = "me-xxl-5"
    case meXxlAuto = "me-xxl-auto"
    case mx0 = "mx-0"
    case mx1 = "mx-1"
    case mx2 = "mx-2"
    case mx3 = "mx-3"
    case mx4 = "mx-4"
    case mx5 = "mx-5"
    case mxAuto = "mx-auto"
    case mxSm0 = "mx-sm-0"
    case mxSm1 = "mx-sm-1"
    case mxSm2 = "mx-sm-2"
    case mxSm3 = "mx-sm-3"
    case mxSm4 = "mx-sm-4"
    case mxSm5 = "mx-sm-5"
    case mxSmAuto = "mx-sm-auto"
    case mxMd0 = "mx-md-0"
    case mxMd1 = "mx-md-1"
    case mxMd2 = "mx-md-2"
    case mxMd3 = "mx-md-3"
    case mxMd4 = "mx-md-4"
    case mxMd5 = "mx-md-5"
    case mxMdAuto = "mx-md-auto"
    case mxLg0 = "mx-lg-0"
    case mxLg1 = "mx-lg-1"
    case mxLg2 = "mx-lg-2"
    case mxLg3 = "mx-lg-3"
    case mxLg4 = "mx-lg-4"
    case mxLg5 = "mx-lg-5"
    case mxLgAuto = "mx-lg-auto"
    case mxXl0 = "mx-xl-0"
    case mxXl1 = "mx-xl-1"
    case mxXl2 = "mx-xl-2"
    case mxXl3 = "mx-xl-3"
    case mxXl4 = "mx-xl-4"
    case mxXl5 = "mx-xl-5"
    case mxXlAuto = "mx-xl-auto"
    case mxXxl0 = "mx-xxl-0"
    case mxXxl1 = "mx-xxl-1"
    case mxXxl2 = "mx-xxl-2"
    case mxXxl3 = "mx-xxl-3"
    case mxXxl4 = "mx-xxl-4"
    case mxXxl5 = "mx-xxl-5"
    case mxXxlAuto = "mx-xxl-auto"
    case my0 = "my-0"
    case my1 = "my-1"
    case my2 = "my-2"
    case my3 = "my-3"
    case my4 = "my-4"
    case my5 = "my-5"
    case myAuto = "my-auto"
    case mySm0 = "my-sm-0"
    case mySm1 = "my-sm-1"
    case mySm2 = "my-sm-2"
    case mySm3 = "my-sm-3"
    case mySm4 = "my-sm-4"
    case mySm5 = "my-sm-5"
    case mySmAuto = "my-sm-auto"
    case myMd0 = "my-md-0"
    case myMd1 = "my-md-1"
    case myMd2 = "my-md-2"
    case myMd3 = "my-md-3"
    case myMd4 = "my-md-4"
    case myMd5 = "my-md-5"
    case myMdAuto = "my-md-auto"
    case myLg0 = "my-lg-0"
    case myLg1 = "my-lg-1"
    case myLg2 = "my-lg-2"
    case myLg3 = "my-lg-3"
    case myLg4 = "my-lg-4"
    case myLg5 = "my-lg-5"
    case myLgAuto = "my-lg-auto"
    case myXl0 = "my-xl-0"
    case myXl1 = "my-xl-1"
    case myXl2 = "my-xl-2"
    case myXl3 = "my-xl-3"
    case myXl4 = "my-xl-4"
    case myXl5 = "my-xl-5"
    case myXlAuto = "my-xl-auto"
    case myXxl0 = "my-xxl-0"
    case myXxl1 = "my-xxl-1"
    case myXxl2 = "my-xxl-2"
    case myXxl3 = "my-xxl-3"
    case myXxl4 = "my-xxl-4"
    case myXxl5 = "my-xxl-5"
    case myXxlAuto = "my-xxl-auto"
    case m0 = "m-0"
    case m1 = "m-1"
    case m2 = "m-2"
    case m3 = "m-3"
    case m4 = "m-4"
    case m5 = "m-5"
    case mAuto = "m-auto"
    case mSm0 = "m-sm-0"
    case mSm1 = "m-sm-1"
    case mSm2 = "m-sm-2"
    case mSm3 = "m-sm-3"
    case mSm4 = "m-sm-4"
    case mSm5 = "m-sm-5"
    case mSmAuto = "m-sm-auto"
    case mMd0 = "m-md-0"
    case mMd1 = "m-md-1"
    case mMd2 = "m-md-2"
    case mMd3 = "m-md-3"
    case mMd4 = "m-md-4"
    case mMd5 = "m-md-5"
    case mMdAuto = "m-md-auto"
    case mLg0 = "m-lg-0"
    case mLg1 = "m-lg-1"
    case mLg2 = "m-lg-2"
    case mLg3 = "m-lg-3"
    case mLg4 = "m-lg-4"
    case mLg5 = "m-lg-5"
    case mLgAuto = "m-lg-auto"
    case mXl0 = "m-xl-0"
    case mXl1 = "m-xl-1"
    case mXl2 = "m-xl-2"
    case mXl3 = "m-xl-3"
    case mXl4 = "m-xl-4"
    case mXl5 = "m-xl-5"
    case mXlAuto = "m-xl-auto"
    case mXxl0 = "m-xxl-0"
    case mXxl1 = "m-xxl-1"
    case mXxl2 = "m-xxl-2"
    case mXxl3 = "m-xxl-3"
    case mXxl4 = "m-xxl-4"
    case mXxl5 = "m-xxl-5"
    case mXxlAuto = "m-xxl-auto"
    
    case mw100 = "mw-100"
    case mh100 = "mh-100"
    
    case mark
    
    // MARK: - N
    case navbar
    case navbarBrand = "navbar-brand"
    case navbarCollapse = "navbar-collapse"
    case navbarDark = "navbar-dark"
    case navbarExpandSm = "navbar-expand-sm"
    case navbarExpandMd = "navbar-expand-md"
    case navbarExpandLg = "navbar-expand-lg"
    case navbarExpandXl = "navbar-expand-xl"
    case navbarExpandXxl = "navbar-expand-xxl"
    case navbarLight = "navbar-light"
    case navbarNav = "navbar-nav"
    case navbarNavScroll = "navbar-nav-scroll"
    case navbarSupportedContent = "navbarSupportedContent"
    case navbarText = "navbar-text"
    case navbarToggler = "navbar-toggler"
    case navbarTogglerIcon = "navbar-toggler-icon"

    case nav
    case navFill = "nav-fill"
    case navItem = "nav-item"
    case navJustified = "nav-justified"
    case navLink = "nav-link"
    case navPills = "nav-pills"
    case navTabs = "nav-tabs"
    case navUnderline = "nav-underline"
    
    case needsValidation = "needs-validation"
    
    // MARK: - O
    
    case opacity100 = "opacity-100"
    case opacity75 = "opacity-75"
    case opacity50 = "opacity-50"
    case opacity25 = "opacity-25"
    
    case order0 = "order-0"
    case order1 = "order-1"
    case order2 = "order-2"
    case order3 = "order-3"
    case order4 = "order-4"
    case order5 = "order-5"
    case orderSm0 = "order-sm-0"
    case orderSm1 = "order-sm-1"
    case orderSm2 = "order-sm-2"
    case orderSm3 = "order-sm-3"
    case orderSm4 = "order-sm-4"
    case orderSm5 = "order-sm-5"
    case orderMd0 = "order-md-0"
    case orderMd1 = "order-md-1"
    case orderMd2 = "order-md-2"
    case orderMd3 = "order-md-3"
    case orderMd4 = "order-md-4"
    case orderMd5 = "order-md-5"
    case orderLg0 = "order-lg-0"
    case orderLg1 = "order-lg-1"
    case orderLg2 = "order-lg-2"
    case orderLg3 = "order-lg-3"
    case orderLg4 = "order-lg-4"
    case orderLg5 = "order-lg-5"
    case orderXl0 = "order-xl-0"
    case orderXl1 = "order-xl-1"
    case orderXl2 = "order-xl-2"
    case orderXl3 = "order-xl-3"
    case orderXl4 = "order-xl-4"
    case orderXl5 = "order-xl-5"
    case orderXxl0 = "order-xxl-0"
    case orderXxl1 = "order-xxl-1"
    case orderXxl2 = "order-xxl-2"
    case orderXxl3 = "order-xxl-3"
    case orderXxl4 = "order-xxl-4"
    case orderXxl5 = "order-xxl-5"
    case orderFirst = "order-first"
    case orderLast = "order-last"
    case orderSmFirst = "order-sm-first"
    case orderSmLast = "order-sm-last"
    case orderMdFirst = "order-md-first"
    case orderMdLast = "order-md-last"
    case orderLgFirst = "order-lg-first"
    case orderLgLast = "order-lg-last"
    case orderXlFirst = "order-xl-first"
    case orderXlLast = "order-xl-last"
    case orderXxlFirst = "order-xxl-first"
    case orderXxlLast = "order-xxl-last"
    
    case offcanvas
    case offcanvasBody = "offcanvas-body"
    case offcanvasHeader = "offcanvas-header"
    case offcanvasBottom = "offcanvas-bottom"
    case offcanvasEnd = "offcanvas-end"
    case offcanvasStart = "offcanvas-start"
    case offcanvasTop = "offcanvas-top"
    case offcanvasTitle = "offcanvas-title"
    
    
    case offset = "offset"
    case offset0 = "offset-0"
    case offset2 = "offset-2"
    case offset3 = "offset-3"
    case offset4 = "offset-4"
    case offset5 = "offset-5"
    case offset6 = "offset-6"
    case offset7 = "offset-7"
    case offset8 = "offset-8"
    case offset9 = "offset-9"
    case offset10 = "offset-10"
    case offset11 = "offset-11"
    case offset12 = "offset-12"
    
    case offsetSm = "offset-sm"
    case offsetSm0 = "offset-sm-0"
    case offsetSm2 = "offset-sm-2"
    case offsetSm3 = "offset-sm-3"
    case offsetSm4 = "offset-sm-4"
    case offsetSm5 = "offset-sm-5"
    case offsetSm6 = "offset-sm-6"
    case offsetSm7 = "offset-sm-7"
    case offsetSm8 = "offset-sm-8"
    case offsetSm9 = "offset-sm-9"
    case offsetSm10 = "offset-sm-10"
    case offsetSm11 = "offset-sm-11"
    case offsetSm12 = "offset-sm-12"
    
    case offsetMd = "offset-md"
    case offsetMd0 = "offset-md-0"
    case offsetMd2 = "offset-md-2"
    case offsetMd3 = "offset-md-3"
    case offsetMd4 = "offset-md-4"
    case offsetMd5 = "offset-md-5"
    case offsetMd6 = "offset-md-6"
    case offsetMd7 = "offset-md-7"
    case offsetMd8 = "offset-md-8"
    case offsetMd9 = "offset-md-9"
    case offsetMd10 = "offset-md-10"
    case offsetMd11 = "offset-md-11"
    case offsetMd12 = "offset-md-12"
    
    case offsetLg = "offset-lg"
    case offsetLg0 = "offset-lg-0"
    case offsetLg2 = "offset-lg-2"
    case offsetLg3 = "offset-lg-3"
    case offsetLg4 = "offset-lg-4"
    case offsetLg5 = "offset-lg-5"
    case offsetLg6 = "offset-lg-6"
    case offsetLg7 = "offset-lg-7"
    case offsetLg8 = "offset-lg-8"
    case offsetLg9 = "offset-lg-9"
    case offsetLg10 = "offset-lg-10"
    case offsetLg11 = "offset-lg-11"
    case offsetLg12 = "offset-lg-12"
    
    case offsetXl = "offset-xl"
    case offsetXl0 = "offset-xl-0"
    case offsetXl2 = "offset-xl-2"
    case offsetXl3 = "offset-xl-3"
    case offsetXl4 = "offset-xl-4"
    case offsetXl5 = "offset-xl-5"
    case offsetXl6 = "offset-xl-6"
    case offsetXl7 = "offset-xl-7"
    case offsetXl8 = "offset-xl-8"
    case offsetXl9 = "offset-xl-9"
    case offsetXl10 = "offset-xl-10"
    case offsetXl11 = "offset-xl-11"
    case offsetXl12 = "offset-xl-12"
    
    case offsetXxl = "offset-xxl"
    case offsetXxl0 = "offset-xxl-0"
    case offsetXxl2 = "offset-xxl-2"
    case offsetXxl3 = "offset-xxl-3"
    case offsetXxl4 = "offset-xxl-4"
    case offsetXxl5 = "offset-xxl-5"
    case offsetXxl6 = "offset-xxl-6"
    case offsetXxl7 = "offset-xxl-7"
    case offsetXxl8 = "offset-xxl-8"
    case offsetXxl9 = "offset-xxl-9"
    case offsetXxl10 = "offset-xxl-10"
    case offsetXxl11 = "offset-xxl-11"
    case offsetXxl12 = "offset-xxl-12"
    
    case textOpacity25 = "text-opacity-25"
    case textOpacity50 = "text-opacity-50"
    case textOpacity75 = "text-opacity-75"
    
    case overflowAuto = "overflow-auto"
    case overflowHidden = "overflow-hidden"
    case overflowVisible = "overflow-visible"
    case overflowScroll = "overflow-scroll"
    
    // MARK: - P
    case pagination
    case pageItem = "page-item"
    case pageLink = "page-link"
    case paginationLg = "pagination-lg"
    case paginationSm = "pagination-sm"
    
    case pill
    
    case placeholder
    case placeholderGlow = "placeholder-glow"
    case placeholderWave = "placeholder-wave"
    case placeholderXs = "placeholder-xs"
    case placeholderSm = "placeholder-sm"
    case placeholderLg = "placeholder-lg"
    
    case popover
    
    case positionStatic = "position-static"
    case positionRelative = "position-relative"
    case positionAbsolute = "position-absolute"
    case positionFixed = "position-fixed"
    case positionSticky = "position-sticky"
    
    case progress
    case progressbar
    case progressBarStriped = "progress-bar-striped"
    case progressBarAnimated = "progress-bar-animated"
    
    case pt0 = "pt-0"
    case pt1 = "pt-1"
    case pt2 = "pt-2"
    case pt3 = "pt-3"
    case pt4 = "pt-4"
    case pt5 = "pt-5"
    case ptAuto = "pt-auto"
    case ptSm0 = "pt-sm-0"
    case ptSm1 = "pt-sm-1"
    case ptSm2 = "pt-sm-2"
    case ptSm3 = "pt-sm-3"
    case ptSm4 = "pt-sm-4"
    case ptSm5 = "pt-sm-5"
    case ptSmAuto = "pt-sm-auto"
    case ptMd0 = "pt-md-0"
    case ptMd1 = "pt-md-1"
    case ptMd2 = "pt-md-2"
    case ptMd3 = "pt-md-3"
    case ptMd4 = "pt-md-4"
    case ptMd5 = "pt-md-5"
    case ptMdAuto = "pt-md-auto"
    case ptLg0 = "pt-lg-0"
    case ptLg1 = "pt-lg-1"
    case ptLg2 = "pt-lg-2"
    case ptLg3 = "pt-lg-3"
    case ptLg4 = "pt-lg-4"
    case ptLg5 = "pt-lg-5"
    case ptLgAuto = "pt-lg-auto"
    case ptXl0 = "pt-xl-0"
    case ptXl1 = "pt-xl-1"
    case ptXl2 = "pt-xl-2"
    case ptXl3 = "pt-xl-3"
    case ptXl4 = "pt-xl-4"
    case ptXl5 = "pt-xl-5"
    case ptXlAuto = "pt-xl-auto"
    case ptXxl0 = "pt-xxl-0"
    case ptXxl1 = "pt-xxl-1"
    case ptXxl2 = "pt-xxl-2"
    case ptXxl3 = "pt-xxl-3"
    case ptXxl4 = "pt-xxl-4"
    case ptXxl5 = "pt-xxl-5"
    case ptXxlAuto = "pt-xxl-auto"
    case pb0 = "pb-0"
    case pb1 = "pb-1"
    case pb2 = "pb-2"
    case pb3 = "pb-3"
    case pb4 = "pb-4"
    case pb5 = "pb-5"
    case pbAuto = "pb-auto"
    case pbSm0 = "pb-sm-0"
    case pbSm1 = "pb-sm-1"
    case pbSm2 = "pb-sm-2"
    case pbSm3 = "pb-sm-3"
    case pbSm4 = "pb-sm-4"
    case pbSm5 = "pb-sm-5"
    case pbSmAuto = "pb-sm-auto"
    case pbMd0 = "pb-md-0"
    case pbMd1 = "pb-md-1"
    case pbMd2 = "pb-md-2"
    case pbMd3 = "pb-md-3"
    case pbMd4 = "pb-md-4"
    case pbMd5 = "pb-md-5"
    case pbMdAuto = "pb-md-auto"
    case pbLg0 = "pb-lg-0"
    case pbLg1 = "pb-lg-1"
    case pbLg2 = "pb-lg-2"
    case pbLg3 = "pb-lg-3"
    case pbLg4 = "pb-lg-4"
    case pbLg5 = "pb-lg-5"
    case pbLgAuto = "pb-lg-auto"
    case pbXl0 = "pb-xl-0"
    case pbXl1 = "pb-xl-1"
    case pbXl2 = "pb-xl-2"
    case pbXl3 = "pb-xl-3"
    case pbXl4 = "pb-xl-4"
    case pbXl5 = "pb-xl-5"
    case pbXlAuto = "pb-xl-auto"
    case pbXxl0 = "pb-xxl-0"
    case pbXxl1 = "pb-xxl-1"
    case pbXxl2 = "pb-xxl-2"
    case pbXxl3 = "pb-xxl-3"
    case pbXxl4 = "pb-xxl-4"
    case pbXxl5 = "pb-xxl-5"
    case pbXxlAuto = "pb-xxl-auto"
    case ps0 = "ps-0"
    case ps1 = "ps-1"
    case ps2 = "ps-2"
    case ps3 = "ps-3"
    case ps4 = "ps-4"
    case ps5 = "ps-5"
    case psAuto = "ps-auto"
    case psSm0 = "ps-sm-0"
    case psSm1 = "ps-sm-1"
    case psSm2 = "ps-sm-2"
    case psSm3 = "ps-sm-3"
    case psSm4 = "ps-sm-4"
    case psSm5 = "ps-sm-5"
    case psSmAuto = "ps-sm-auto"
    case psMd0 = "ps-md-0"
    case psMd1 = "ps-md-1"
    case psMd2 = "ps-md-2"
    case psMd3 = "ps-md-3"
    case psMd4 = "ps-md-4"
    case psMd5 = "ps-md-5"
    case psMdAuto = "ps-md-auto"
    case psLg0 = "ps-lg-0"
    case psLg1 = "ps-lg-1"
    case psLg2 = "ps-lg-2"
    case psLg3 = "ps-lg-3"
    case psLg4 = "ps-lg-4"
    case psLg5 = "ps-lg-5"
    case psLgAuto = "ps-lg-auto"
    case psXl0 = "ps-xl-0"
    case psXl1 = "ps-xl-1"
    case psXl2 = "ps-xl-2"
    case psXl3 = "ps-xl-3"
    case psXl4 = "ps-xl-4"
    case psXl5 = "ps-xl-5"
    case psXlAuto = "ps-xl-auto"
    case psXxl0 = "ps-xxl-0"
    case psXxl1 = "ps-xxl-1"
    case psXxl2 = "ps-xxl-2"
    case psXxl3 = "ps-xxl-3"
    case psXxl4 = "ps-xxl-4"
    case psXxl5 = "ps-xxl-5"
    case psXxlAuto = "ps-xxl-auto"
    case pe0 = "pe-0"
    case pe1 = "pe-1"
    case pe2 = "pe-2"
    case pe3 = "pe-3"
    case pe4 = "pe-4"
    case pe5 = "pe-5"
    case peAuto = "pe-auto"
    case peSm0 = "pe-sm-0"
    case peSm1 = "pe-sm-1"
    case peSm2 = "pe-sm-2"
    case peSm3 = "pe-sm-3"
    case peSm4 = "pe-sm-4"
    case peSm5 = "pe-sm-5"
    case peSmAuto = "pe-sm-auto"
    case peMd0 = "pe-md-0"
    case peMd1 = "pe-md-1"
    case peMd2 = "pe-md-2"
    case peMd3 = "pe-md-3"
    case peMd4 = "pe-md-4"
    case peMd5 = "pe-md-5"
    case peMdAuto = "pe-md-auto"
    case peLg0 = "pe-lg-0"
    case peLg1 = "pe-lg-1"
    case peLg2 = "pe-lg-2"
    case peLg3 = "pe-lg-3"
    case peLg4 = "pe-lg-4"
    case peLg5 = "pe-lg-5"
    case peLgAuto = "pe-lg-auto"
    case peXl0 = "pe-xl-0"
    case peXl1 = "pe-xl-1"
    case peXl2 = "pe-xl-2"
    case peXl3 = "pe-xl-3"
    case peXl4 = "pe-xl-4"
    case peXl5 = "pe-xl-5"
    case peXlAuto = "pe-xl-auto"
    case peXxl0 = "pe-xxl-0"
    case peXxl1 = "pe-xxl-1"
    case peXxl2 = "pe-xxl-2"
    case peXxl3 = "pe-xxl-3"
    case peXxl4 = "pe-xxl-4"
    case peXxl5 = "pe-xxl-5"
    case peXxlAuto = "pe-xxl-auto"
    case px0 = "px-0"
    case px1 = "px-1"
    case px2 = "px-2"
    case px3 = "px-3"
    case px4 = "px-4"
    case px5 = "px-5"
    case pxAuto = "px-auto"
    case pxSm0 = "px-sm-0"
    case pxSm1 = "px-sm-1"
    case pxSm2 = "px-sm-2"
    case pxSm3 = "px-sm-3"
    case pxSm4 = "px-sm-4"
    case pxSm5 = "px-sm-5"
    case pxSmAuto = "px-sm-auto"
    case pxMd0 = "px-md-0"
    case pxMd1 = "px-md-1"
    case pxMd2 = "px-md-2"
    case pxMd3 = "px-md-3"
    case pxMd4 = "px-md-4"
    case pxMd5 = "px-md-5"
    case pxMdAuto = "px-md-auto"
    case pxLg0 = "px-lg-0"
    case pxLg1 = "px-lg-1"
    case pxLg2 = "px-lg-2"
    case pxLg3 = "px-lg-3"
    case pxLg4 = "px-lg-4"
    case pxLg5 = "px-lg-5"
    case pxLgAuto = "px-lg-auto"
    case pxXl0 = "px-xl-0"
    case pxXl1 = "px-xl-1"
    case pxXl2 = "px-xl-2"
    case pxXl3 = "px-xl-3"
    case pxXl4 = "px-xl-4"
    case pxXl5 = "px-xl-5"
    case pxXlAuto = "px-xl-auto"
    case pxXxl0 = "px-xxl-0"
    case pxXxl1 = "px-xxl-1"
    case pxXxl2 = "px-xxl-2"
    case pxXxl3 = "px-xxl-3"
    case pxXxl4 = "px-xxl-4"
    case pxXxl5 = "px-xxl-5"
    case pxXxlAuto = "px-xxl-auto"
    case py0 = "py-0"
    case py1 = "py-1"
    case py2 = "py-2"
    case py3 = "py-3"
    case py4 = "py-4"
    case py5 = "py-5"
    case pyAuto = "py-auto"
    case pySm0 = "py-sm-0"
    case pySm1 = "py-sm-1"
    case pySm2 = "py-sm-2"
    case pySm3 = "py-sm-3"
    case pySm4 = "py-sm-4"
    case pySm5 = "py-sm-5"
    case pySmAuto = "py-sm-auto"
    case pyMd0 = "py-md-0"
    case pyMd1 = "py-md-1"
    case pyMd2 = "py-md-2"
    case pyMd3 = "py-md-3"
    case pyMd4 = "py-md-4"
    case pyMd5 = "py-md-5"
    case pyMdAuto = "py-md-auto"
    case pyLg0 = "py-lg-0"
    case pyLg1 = "py-lg-1"
    case pyLg2 = "py-lg-2"
    case pyLg3 = "py-lg-3"
    case pyLg4 = "py-lg-4"
    case pyLg5 = "py-lg-5"
    case pyLgAuto = "py-lg-auto"
    case pyXl0 = "py-xl-0"
    case pyXl1 = "py-xl-1"
    case pyXl2 = "py-xl-2"
    case pyXl3 = "py-xl-3"
    case pyXl4 = "py-xl-4"
    case pyXl5 = "py-xl-5"
    case pyXlAuto = "py-xl-auto"
    case pyXxl0 = "py-xxl-0"
    case pyXxl1 = "py-xxl-1"
    case pyXxl2 = "py-xxl-2"
    case pyXxl3 = "py-xxl-3"
    case pyXxl4 = "py-xxl-4"
    case pyXxl5 = "py-xxl-5"
    case pyXxlAuto = "py-xxl-auto"
    case p0 = "p-0"
    case p1 = "p-1"
    case p2 = "p-2"
    case p3 = "p-3"
    case p4 = "p-4"
    case p5 = "p-5"
    case pAuto = "p-auto"
    case pSm0 = "p-sm-0"
    case pSm1 = "p-sm-1"
    case pSm2 = "p-sm-2"
    case pSm3 = "p-sm-3"
    case pSm4 = "p-sm-4"
    case pSm5 = "p-sm-5"
    case pSmAuto = "p-sm-auto"
    case pMd0 = "p-md-0"
    case pMd1 = "p-md-1"
    case pMd2 = "p-md-2"
    case pMd3 = "p-md-3"
    case pMd4 = "p-md-4"
    case pMd5 = "p-md-5"
    case pMdAuto = "p-md-auto"
    case pLg0 = "p-lg-0"
    case pLg1 = "p-lg-1"
    case pLg2 = "p-lg-2"
    case pLg3 = "p-lg-3"
    case pLg4 = "p-lg-4"
    case pLg5 = "p-lg-5"
    case pLgAuto = "p-lg-auto"
    case pXl0 = "p-xl-0"
    case pXl1 = "p-xl-1"
    case pXl2 = "p-xl-2"
    case pXl3 = "p-xl-3"
    case pXl4 = "p-xl-4"
    case pXl5 = "p-xl-5"
    case pXlAuto = "p-xl-auto"
    case pXxl0 = "p-xxl-0"
    case pXxl1 = "p-xxl-1"
    case pXxl2 = "p-xxl-2"
    case pXxl3 = "p-xxl-3"
    case pXxl4 = "p-xxl-4"
    case pXxl5 = "p-xxl-5"
    case pXxlAuto = "p-xxl-auto"
    
    // MARK: - R
    case right = "right"
    case rotate90 = "rotate-90"
    case rotate180 = "rotate-180"
    case rotate270 = "rotate-270"
    case rounded
    case roundedTop = "rounded-top"
    case roundedEnd = "rounded-end"
    case roundedBottom = "rounded-bottom"
    case roundedStart = "rounded-start"
    case roundedCircle = "rounded-circle"
    case roundedPill = "rounded-pill"
    
    case rounded0 = "rounded-0"
    case rounded1 = "rounded-1"
    case rounded2 = "rounded-2"
    case rounded3 = "rounded-3"
    
    case row
    
    case rowColsAuto = "row-cols-auto"
    case rowColsSmAuto = "row-cols-sm-auto"
    case rowColsMdAuto = "row-cols-md-auto"
    case rowColsLgAuto = "row-cols-lg-auto"
    case rowColsXlAuto = "row-cols-xl-auto"
    case rowColsXxlAuto = "row-cols-xxl-auto"
    
    case rowCols1 = "row-cols-1"
    case rowColsSm1 = "row-cols-sm-1"
    case rowColsMd1 = "row-cols-md-1"
    case rowColsLg1 = "row-cols-lg-1"
    case rowColsXl1 = "row-cols-xl-1"
    case rowColsXxl1 = "row-cols-xxl-1"
    
    case rowCols2 = "row-cols-2"
    case rowColsSm2 = "row-cols-sm-2"
    case rowColsMd2 = "row-cols-md-2"
    case rowColsLg2 = "row-cols-lg-2"
    case rowColsXl2 = "row-cols-xl-2"
    case rowColsXxl2 = "row-cols-xxl-2"
    
    case rowCols3 = "row-cols-3"
    case rowColsSm3 = "row-cols-sm-3"
    case rowColsMd3 = "row-cols-md-3"
    case rowColsLg3 = "row-cols-lg-3"
    case rowColsXl3 = "row-cols-xl-3"
    case rowColsXxl3 = "row-cols-xxl-3"
    
    case rowCols4 = "row-cols-4"
    case rowColsSm4 = "row-cols-sm-4"
    case rowColsMd4 = "row-cols-md-4"
    case rowColsLg4 = "row-cols-lg-4"
    case rowColsXl4 = "row-cols-xl-4"
    case rowColsXxl4 = "row-cols-xxl-4"
    
    case rowCols5 = "row-cols-5"
    case rowColsSm5 = "row-cols-sm-5"
    case rowColsMd5 = "row-cols-md-5"
    case rowColsLg5 = "row-cols-lg-5"
    case rowColsXl5 = "row-cols-xl-5"
    case rowColsXxl5 = "row-cols-xxl-5"
    
    case rowCols6 = "row-cols-6"
    case rowColsSm6 = "row-cols-sm-6"
    case rowColsMd6 = "row-cols-md-6"
    case rowColsLg6 = "row-cols-lg-6"
    case rowColsXl6 = "row-cols-xl-6"
    case rowColsXxl6 = "row-cols-xxl-6"
    
    case rowCols7 = "row-cols-7"
    case rowColsSm7 = "row-cols-sm-7"
    case rowColsMd7 = "row-cols-md-7"
    case rowColsLg7 = "row-cols-lg-7"
    case rowColsXl7 = "row-cols-xl-7"
    case rowColsXxl7 = "row-cols-xxl-7"
    
    case rowCols8 = "row-cols-8"
    case rowColsSm8 = "row-cols-sm-8"
    case rowColsMd8 = "row-cols-md-8"
    case rowColsLg8 = "row-cols-lg-8"
    case rowColsXl8 = "row-cols-xl-8"
    case rowColsXxl8 = "row-cols-xxl-8"
    
    case rowCols9 = "row-cols-9"
    case rowColsSm9 = "row-cols-sm-9"
    case rowColsMd9 = "row-cols-md-9"
    case rowColsLg9 = "row-cols-lg-9"
    case rowColsXl9 = "row-cols-xl-9"
    case rowColsXxl9 = "row-cols-xxl-9"
    
    case rowCols10 = "row-cols-10"
    case rowColsSm10 = "row-cols-sm-10"
    case rowColsMd10 = "row-cols-md-10"
    case rowColsLg10 = "row-cols-lg-10"
    case rowColsXl10 = "row-cols-xl-10"
    case rowColsXxl10 = "row-cols-xxl-10"
    
    case rowCols11 = "row-cols-11"
    case rowColsSm11 = "row-cols-sm-11"
    case rowColsMd11 = "row-cols-md-11"
    case rowColsLg11 = "row-cols-lg-11"
    case rowColsXl11 = "row-cols-xl-11"
    case rowColsXxl11 = "row-cols-xxl-11"
    
    case rowCols12 = "row-cols-12"
    case rowColsSm12 = "row-cols-sm-12"
    case rowColsMd12 = "row-cols-md-12"
    case rowColsLg12 = "row-cols-lg-12"
    case rowColsXl12 = "row-cols-xl-12"
    case rowColsXxl12 = "row-cols-xxl-12"
    
    // MARK: - S
    case select
    case scroll
    
    case shadowNone = "shadow-none"
    case shadowSm = "shadow-sm"
    case shadow
    case shadowLg = "shadow-lg"
    
    case show
    
    case slide
    
    case small
    
    case spinnerBorder = "spinner-border"
    case spinnerGrow = "spinner-grow"
    case spinnerBorderSm = "spinner-border-sm"
    case spinnerGrowSm = "spinner-grow-sm"
    
    case srOnly = "sr-only"
    
    case start0 = "start-0"
    case start50 = "start-50"
    case start100 = "start-100"
    
    case `static`
    
    case stickyTop = "sticky-top"   //! Not fully supported in every browser
    case stretchedLink = "stretched-link"
    
    // MARK: - T
    case tab
    case tabContent = "tab-content"
    case tabPane = "tab-pane"
    case table
    case tableActive = "table-active"
    case tableBordered = "table-bordered"
    case tableBorderless = "table-borderless"
    case tableDanger = "table-danger"
    case tableDark = "table-dark"
    case tableInfo = "table-info"
    case tableLight = "table-light"
    case tablePrimary = "table-primary"
    case tableSecondary = "table-secondary"
    case tableSuccess = "table-success"
    case tableWarning = "table-warning"
    case tableStriped = "table-striped"
    case tableHover = "table-hover"
    case tableResponsive = "table-responsive"
    case tableResponsiveSm = "table-responsive-sm"
    case tableResponsiveMd = "table-responsive-md"
    case tableResponsiveLg = "table-responsive-lg"
    case tableResponsiveXl = "table-responsive-xl"
    case tableResponsiveXxl = "table-responsive-xxl"
    case tableSm = "table-sm"
    
    case textBreak = "text-break"
    case textDecorationUnderline = "text-decoration-underline"
    case textDecorationLineThrough = "text-decoration-line-through"
    case textDecorationNone = "text-decoration-none"
    case textWrap = "text-wrap"
    case textNowrap = "text-nowrap"
    case textTruncate = "text-truncate"
    
    case textLowercase = "text-lowercase"
    case textUppercase = "text-uppercase"
    case textCapitalize = "text-capitalize"
    
    case textReset = "text-reset"
    
    case textStart = "text-start"
    case textSmStart = "text-sm-start"
    case textMdStart = "text-md-start"
    case textLgStart = "text-lg-start"
    case textXlStart = "text-xl-start"
    case textCenter = "text-center"
    case textSmCenter = "text-sm-center"
    case textMdCenter = "text-md-center"
    case textLgCenter = "text-lg-center"
    case textXlCenter = "text-xl-center"
    case textEnd = "text-end"
    case textSmEnd = "text-sm-end"
    case textMdEnd = "text-md-end"
    case textLgEnd = "text-lg-end"
    case textXlEnd = "text-xl-end"
    
    case textPrimary = "text-primary"
    case textSecondary = "text-secondary"
    case textSuccess = "text-success"
    case textDanger = "text-danger"
    case textWarning = "text-warning"
    case textInfo = "text-info"
    case textLight = "text-light"
    case textDark = "text-dark"
    case textWhite = "text-white"
    case textBody = "text-body"
    case textMuted = "text-muted"
    
    case toast
    case toastHeader = "toast-header"
    case toastBody = "toast-body"
    case toastContainer = "toast-container"
    
    case top0 = "top-0"
    case top50 = "top-50"
    case top100 = "top-100"
    
    case tooltip
    
    case translateMiddle = "translate-middle"
    case translateMiddleX = "translate-middle-x"
    case translateMiddleY = "translate-middle-y"

    case trClickable = "tr-clickable"
    
    // MARK: - U
    case userSelectAll = "user-select-all"
    case userSelectAuto = "user-select-auto"
    case userSelectNone = "user-select-none"
    
    // MARK: - V
    case validFeedback = "valid-feedback"
    case validTooltip = "valid-tooltip"
    
    case visible
    case visuallyHidden = "visually-hidden"
    case visuallyHiddenFocusable = "visually-hidden-focusable"
    case vr
    case vstack
    
    // MARK: - W
    case wasValidated = "was-validated"
    
    case w25 = "w-25"
    case w50 = "w-50"
    case w75 = "w-75"
    case w100 = "w-100"
    case wAuto = "w-auto"
}
